In [31]:
#importing necessary libraries
import numpy as np
import pandas as pd



In [32]:
#Loading the dataset
train_data = pd.read_csv('data/train.csv')
train_data.head()

test_data = pd.read_csv('data/test.csv')
test_data.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 784 columns]

In [33]:
#Separating target and features
y = train_data['label']
x = train_data.drop('label', axis=1)	
x.head

<bound method NDFrame.head of        pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0           0       0       0       0       0       0       0       0       0   
1           0       0       0       0       0       0       0       0       0   
2           0       0       0       0       0       0       0       0       0   
3           0       0       0       0       0       0       0       0       0   
4           0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995       0       0       0       0       0       0       0       0       0   
41996       0       0       0       0       0       0       0       0       0   
41997       0       0       0       0       0       0       0       0       0   
41998       0       0       0       0       0       0       0       0       0   
41999       0       0       0       0       0       0       0       0       0  

In [34]:
#normalizing the x values
x = x/255.0
test_data = test_data/255.0



In [35]:
#reshaping the x values
x = x.values.reshape(-1,28,28,1)
test_data = test_data.values.reshape(-1,28,28,1)
print(x)

[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.

In [36]:
# Data Augmentation
#from tensorflow.keras.preprocessing.image import ImageDataGenerator

#datagen = ImageDataGenerator(
 #   rotation_range=10,
  #  zoom_range=0.1,
   # width_shift_range=0.1,
    #height_shift_range=0.1
#)
#datagen.fit(x)

In [37]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
#import BatchNormalization
from tensorflow.keras.layers import BatchNormalization

# Build the model
model = Sequential([
    Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=(28, 28, 1)),
    BatchNormalization(),
    MaxPooling2D(pool_size=(2, 2)),
    Flatten(),
    Dense(128, activation='relu'),
    BatchNormalization(),
    Dense(64, activation='relu'),
    BatchNormalization(),
    Dense(10, activation='softmax')
])

In [38]:
#Define loss function

from tensorflow.keras import losses
from tensorflow.keras.optimizers import Adam

# Defining the optimizer with an adjusted learning rate
loss = losses.SparseCategoricalCrossentropy(from_logits=True)
model.compile(optimizer=Adam(learning_rate=0.001),
              loss=loss,
              metrics=['accuracy'])

In [39]:
#fitting model
model.fit(x, y, epochs=10)

Epoch 1/10
1313/1313 [==============================] - 32s 24ms/step - loss: 1.5225 - accuracy: 0.9509
Epoch 2/10
1313/1313 [==============================] - 31s 24ms/step - loss: 1.4850 - accuracy: 0.9790
Epoch 3/10
1313/1313 [==============================] - 31s 23ms/step - loss: 1.4801 - accuracy: 0.9830
Epoch 4/10
1313/1313 [==============================] - 31s 23ms/step - loss: 1.4759 - accuracy: 0.9865
Epoch 5/10
1313/1313 [==============================] - 32s 24ms/step - loss: 1.4740 - accuracy: 0.9883
Epoch 6/10
1313/1313 [==============================] - 33s 25ms/step - loss: 1.4733 - accuracy: 0.9888
Epoch 7/10
1313/1313 [==============================] - 31s 24ms/step - loss: 1.4715 - accuracy: 0.9904
Epoch 8/10
1313/1313 [==============================] - 38s 29ms/step - loss: 1.4713 - accuracy: 0.9904
Epoch 9/10
1313/1313 [==============================] - 31s 23ms/step - loss: 1.4695 - accuracy: 0.9923
Epoch 10/10
1313/1313 [==============================] - 31s 24m

In [40]:
# get predictions
predictions = model.predict(test_data,verbose=1)

# Convert probabilities to class labels
class_labels = np.argmax(predictions, axis=1)

# create a dataframe with the ImageId and the predictions
submission = pd.DataFrame({"ImageId": range(1, len(predictions) + 1), "Label": class_labels})



# save the dataframe to a csv file
submission.to_csv("data/submission.csv", index=False)

875/875 [==============================] - 4s 5ms/step
